### ISSUE TITLE
[Feature] Need Support Firefox

### ISSUE THREAD

**Issue by mnyon** [AHCorn/Bilibili-To-Raindrop#2]
Really thanks for the greatwork! But I did't use the raindrop so if there is a way to export firefox format would be nice.Thanks again✈

**Comment by AHCorn** [comment]
Do you mean exporting to the Json format file used by Firefox bookmark backup? I will check it out. If it can be done, I will merge the Tampermonkey script version of this repository and the part of exporting to Firefox into a new repository in the next week. 
![fdffcda95611233560fe885d9af55b79](https://github.com/AHCorn/Bilibili-To-Raindrop/assets/42889600/edf6b6fc-6707-4e34-b32f-4f86c55d49a8)

**Comment by AHCorn** [comment]
However, I just downloaded the Firefox Developer Edition and found that the format of the LibreWolf version I use is different from the latest version of Firefox. I will use the HTML format of the Firefox Developer Edition as a reference.

**Comment by mnyon** [comment]
> However, I just downloaded the Firefox Developer Edition and found that the format of the LibreWolf version I use is different from the latest version of Firefox. I will use the HTML format of the Firefox Developer Edition as a reference.

Yes! That's it. It would be great convenient

**Comment by AHCorn** [comment]
Hello, I have done my best to complete the script overnight within this week as agreed, but its usability still needs to be tested by more users. 

You can visit https://github.com/AHCorn/Bilibili-Favlist-Export/ to check it out. 

The HTML export uses Firefox's backup format. The two text boxes require the bookmark root directory (which, in my personal testing, seemed to have no actual effect) and the parent directory of the favorite folder.

If you are using Tampermonkey instead of Violentmonkey, please make sure to grant popup window permissions to the Bilibili page before exporting. 

I am not sure if your native language is Chinese or English. Due to my limited ability, I may not be able to adapt to other languages, so please try to use a translation tool to view and use it.
